// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: pkg/distributed/remote/pb/fftb.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotifyRequest_Step int32

const (
	NotifyRequest_UNKNOWN           NotifyRequest_Step = 0
	NotifyRequest_DOWNLOADING_INPUT NotifyRequest_Step = 1
	NotifyRequest_PROCESSING        NotifyRequest_Step = 2
	NotifyRequest_UPLOADING_OUTPUT  NotifyRequest_Step = 3
)

// Enum value maps for NotifyRequest_Step.
var (
	NotifyRequest_Step_name = map[int32]string{
		0: "UNKNOWN",
		1: "DOWNLOADING_INPUT",
		2: "PROCESSING",
		3: "UPLOADING_OUTPUT",
	}
	NotifyRequest_Step_value = map[string]int32{
		"UNKNOWN":           0,
		"DOWNLOADING_INPUT": 1,
		"PROCESSING":        2,
		"UPLOADING_OUTPUT":  3,
	}
)

func (x NotifyRequest_Step) Enum() *NotifyRequest_Step {
	p := new(NotifyRequest_Step)
	*p = x
	return p
}

func (x NotifyRequest_Step) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotifyRequest_Step) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_distributed_remote_pb_fftb_proto_enumTypes[0].Descriptor()
}

func (NotifyRequest_Step) Type() protoreflect.EnumType {
	return &file_pkg_distributed_remote_pb_fftb_proto_enumTypes[0]
}

func (x NotifyRequest_Step) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotifyRequest_Step.Descriptor instead.
func (NotifyRequest_Step) EnumDescriptor() ([]byte, []int) {
	return file_pkg_distributed_remote_pb_fftb_proto_rawDescGZIP(), []int{0, 0}
}

type Task_TaskType int32

const (
	Task_UNKNOWN       Task_TaskType = 0
	Task_CONVERT_V1    Task_TaskType = 1
	Task_MEDIA_META_V1 Task_TaskType = 2
)

// Enum value maps for Task_TaskType.
var (
	Task_TaskType_name = map[int32]string{
		0: "UNKNOWN",
		1: "CONVERT_V1",
		2: "MEDIA_META_V1",
	}
	Task_TaskType_value = map[string]int32{
		"UNKNOWN":       0,
		"CONVERT_V1":    1,
		"MEDIA_META_V1": 2,
	}
)

func (x Task_TaskType) Enum() *Task_TaskType {
	p := new(Task_TaskType)
	*p = x
	return p
}

func (x Task_TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Task_TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_distributed_remote_pb_fftb_proto_enumTypes[1].Descriptor()
}

func (Task_TaskType) Type() protoreflect.EnumType {
	return &file_pkg_distributed_remote_pb_fftb_proto_enumTypes[1]
}

func (x Task_TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Task_TaskType.Descriptor instead.
func (Task_TaskType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_distributed_remote_pb_fftb_proto_rawDescGZIP(), []int{5, 0}
}

type NotifyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Step          NotifyRequest_Step `protobuf:"varint,1,opt,name=step,proto3,enum=NotifyRequest_Step" json:"step,omitempty"`
	Authorization string             `protobuf:"bytes,2,opt,name=authorization,proto3" json:"authorization,omitempty"`
	TaskId        string             `protobuf:"bytes,3,opt,name=taskId,proto3" json:"taskId,omitempty"`
	// value from 0 to 1
	Progress        float64              `protobuf:"fixed64,4,opt,name=progress,proto3" json:"progress,omitempty"`
	ConvertProgress *ConvertTaskProgress `protobuf:"bytes,5,opt,name=convertProgress,proto3" json:"convertProgress,omitempty"`
}

func (x *NotifyRequest) Reset() {
	*x = NotifyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_distributed_remote_pb_fftb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyRequest) ProtoMessage() {}

func (x *NotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_distributed_remote_pb_fftb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyRequest.ProtoReflect.Descriptor instead.
func (*NotifyRequest) Descriptor() ([]byte, []int) {
	return file_pkg_distributed_remote_pb_fftb_proto_rawDescGZIP(), []int{0}
}

func (x *NotifyRequest) GetStep() NotifyRequest_Step {
	if x != nil {
		return x.Step
	}
	return NotifyRequest_UNKNOWN
}

func (x *NotifyRequest) GetAuthorization() string {
	if x != nil {
		return x.Authorization
	}
	return ""
}

func (x *NotifyRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *NotifyRequest) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *NotifyRequest) GetConvertProgress() *ConvertTaskProgress {
	if x != nil {
		return x.ConvertProgress
	}
	return nil
}

type FinishTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Authorization string `protobuf:"bytes,1,opt,name=authorization,proto3" json:"authorization,omitempty"`
	TaskId        string `protobuf:"bytes,2,opt,name=taskId,proto3" json:"taskId,omitempty"`
}

func (x *FinishTaskRequest) Reset() {
	*x = FinishTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_distributed_remote_pb_fftb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinishTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishTaskRequest) ProtoMessage() {}

func (x *FinishTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_distributed_remote_pb_fftb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishTaskRequest.ProtoReflect.Descriptor instead.
func (*FinishTaskRequest) Descriptor() ([]byte, []int) {
	return file_pkg_distributed_remote_pb_fftb_proto_rawDescGZIP(), []int{1}
}

func (x *FinishTaskRequest) GetAuthorization() string {
	if x != nil {
		return x.Authorization
	}
	return ""
}

func (x *FinishTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type QuitTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Authorization string `protobuf:"bytes,1,opt,name=authorization,proto3" json:"authorization,omitempty"`
	TaskId        string `protobuf:"bytes,2,opt,name=taskId,proto3" json:"taskId,omitempty"`
}

func (x *QuitTaskRequest) Reset() {
	*x = QuitTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_distributed_remote_pb_fftb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuitTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuitTaskRequest) ProtoMessage() {}

func (x *QuitTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_distributed_remote_pb_fftb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuitTaskRequest.ProtoReflect.Descriptor instead.
func (*QuitTaskRequest) Descriptor() ([]byte, []int) {
	return file_pkg_distributed_remote_pb_fftb_proto_rawDescGZIP(), []int{2}
}

func (x *QuitTaskRequest) GetAuthorization() string {
	if x != nil {
		return x.Authorization
	}
	return ""
}

func (x *QuitTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type FailTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Authorization string   `protobuf:"bytes,1,opt,name=authorization,proto3" json:"authorization,omitempty"`
	TaskId        string   `protobuf:"bytes,2,opt,name=taskId,proto3" json:"taskId,omitempty"`
	Failures      []string `protobuf:"bytes,3,rep,name=failures,proto3" json:"failures,omitempty"`
}

func (x *FailTaskRequest) Reset() {
	*x = FailTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_distributed_remote_pb_fftb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FailTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailTaskRequest) ProtoMessage() {}

func (x *FailTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_distributed_remote_pb_fftb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailTaskRequest.ProtoReflect.Descriptor instead.
func (*FailTaskRequest) Descriptor() ([]byte, []int) {
	return file_pkg_distributed_remote_pb_fftb_proto_rawDescGZIP(), []int{3}
}

func (x *FailTaskRequest) GetAuthorization() string {
	if x != nil {
		return x.Authorization
	}
	return ""
}

func (x *FailTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *FailTaskRequest) GetFailures() []string {
	if x != nil {
		return x.Failures
	}
	return nil
}

type FindFreeTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Authorization string `protobuf:"bytes,1,opt,name=authorization,proto3" json:"authorization,omitempty"`
}

func (x *FindFreeTaskRequest) Reset() {
	*x = FindFreeTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_distributed_remote_pb_fftb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindFreeTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindFreeTaskRequest) ProtoMessage() {}

func (x *FindFreeTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_distributed_remote_pb_fftb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindFreeTaskRequest.ProtoReflect.Descriptor instead.
func (*FindFreeTaskRequest) Descriptor() ([]byte, []int) {
	return file_pkg_distributed_remote_pb_fftb_proto_rawDescGZIP(), []int{4}
}

func (x *FindFreeTaskRequest) GetAuthorization() string {
	if x != nil {
		return x.Authorization
	}
	return ""
}

type Task struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type            Task_TaskType        `protobuf:"varint,1,opt,name=type,proto3,enum=Task_TaskType" json:"type,omitempty"`
	Id              string               `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	ConvertParams   *ConvertTaskParams   `protobuf:"bytes,4,opt,name=convertParams,proto3" json:"convertParams,omitempty"`
	MediaMetaParams *MediaMetaTaskParams `protobuf:"bytes,5,opt,name=mediaMetaParams,proto3" json:"mediaMetaParams,omitempty"`
}

func (x *Task) Reset() {
	*x = Task{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_distributed_remote_pb_fftb_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_distributed_remote_pb_fftb_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_pkg_distributed_remote_pb_fftb_proto_rawDescGZIP(), []int{5}
}

func (x *Task) GetType() Task_TaskType {
	if x != nil {
		return x.Type
	}
	return Task_UNKNOWN
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetConvertParams() *ConvertTaskParams {
	if x != nil {
		return x.ConvertParams
	}
	return nil
}

func (x *Task) GetMediaMetaParams() *MediaMetaTaskParams {
	if x != nil {
		return x.MediaMetaParams
	}
	return nil
}

type ConvertTaskParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InputRclonePath  string   `protobuf:"bytes,1,opt,name=inputRclonePath,proto3" json:"inputRclonePath,omitempty"`
	OutputRclonePath string   `protobuf:"bytes,2,opt,name=outputRclonePath,proto3" json:"outputRclonePath,omitempty"`
	Opts             []string `protobuf:"bytes,3,rep,name=opts,proto3" json:"opts,omitempty"`
}

func (x *ConvertTaskParams) Reset() {
	*x = ConvertTaskParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_distributed_remote_pb_fftb_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConvertTaskParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertTaskParams) ProtoMessage() {}

func (x *ConvertTaskParams) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_distributed_remote_pb_fftb_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertTaskParams.ProtoReflect.Descriptor instead.
func (*ConvertTaskParams) Descriptor() ([]byte, []int) {
	return file_pkg_distributed_remote_pb_fftb_proto_rawDescGZIP(), []int{6}
}

func (x *ConvertTaskParams) GetInputRclonePath() string {
	if x != nil {
		return x.InputRclonePath
	}
	return ""
}

func (x *ConvertTaskParams) GetOutputRclonePath() string {
	if x != nil {
		return x.OutputRclonePath
	}
	return ""
}

func (x *ConvertTaskParams) GetOpts() []string {
	if x != nil {
		return x.Opts
	}
	return nil
}

type MediaMetaTaskParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InputRclonePath  string `protobuf:"bytes,1,opt,name=inputRclonePath,proto3" json:"inputRclonePath,omitempty"`
	OutputRclonePath string `protobuf:"bytes,2,opt,name=outputRclonePath,proto3" json:"outputRclonePath,omitempty"`
}

func (x *MediaMetaTaskParams) Reset() {
	*x = MediaMetaTaskParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_distributed_remote_pb_fftb_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MediaMetaTaskParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaMetaTaskParams) ProtoMessage() {}

func (x *MediaMetaTaskParams) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_distributed_remote_pb_fftb_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaMetaTaskParams.ProtoReflect.Descriptor instead.
func (*MediaMetaTaskParams) Descriptor() ([]byte, []int) {
	return file_pkg_distributed_remote_pb_fftb_proto_rawDescGZIP(), []int{7}
}

func (x *MediaMetaTaskParams) GetInputRclonePath() string {
	if x != nil {
		return x.InputRclonePath
	}
	return ""
}

func (x *MediaMetaTaskParams) GetOutputRclonePath() string {
	if x != nil {
		return x.OutputRclonePath
	}
	return ""
}

type ConvertTaskProgress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fps   float64 `protobuf:"fixed64,1,opt,name=fps,proto3" json:"fps,omitempty"`
	Frame int64   `protobuf:"varint,2,opt,name=frame,proto3" json:"frame,omitempty"`
	// example: 0.5 is half speed from input file realtime
	Speed float64 `protobuf:"fixed64,3,opt,name=speed,proto3" json:"speed,omitempty"`
	// in bits per second
	Bitrate float64 `protobuf:"fixed64,4,opt,name=bitrate,proto3" json:"bitrate,omitempty"`
	// in milliseconds
	Time int64 `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *ConvertTaskProgress) Reset() {
	*x = ConvertTaskProgress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_distributed_remote_pb_fftb_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConvertTaskProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertTaskProgress) ProtoMessage() {}

func (x *ConvertTaskProgress) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_distributed_remote_pb_fftb_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertTaskProgress.ProtoReflect.Descriptor instead.
func (*ConvertTaskProgress) Descriptor() ([]byte, []int) {
	return file_pkg_distributed_remote_pb_fftb_proto_rawDescGZIP(), []int{8}
}

func (x *ConvertTaskProgress) GetFps() float64 {
	if x != nil {
		return x.Fps
	}
	return 0
}

func (x *ConvertTaskProgress) GetFrame() int64 {
	if x != nil {
		return x.Frame
	}
	return 0
}

func (x *ConvertTaskProgress) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *ConvertTaskProgress) GetBitrate() float64 {
	if x != nil {
		return x.Bitrate
	}
	return 0
}

func (x *ConvertTaskProgress) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_distributed_remote_pb_fftb_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_distributed_remote_pb_fftb_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pkg_distributed_remote_pb_fftb_proto_rawDescGZIP(), []int{9}
}

var File_pkg_distributed_remote_pb_fftb_proto protoreflect.FileDescriptor

var file_pkg_distributed_remote_pb_fftb_proto_rawDesc = []byte{
	0x0a, 0x24, 0x70, 0x6b, 0x67, 0x2f, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x64, 0x2f, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x2f, 0x70, 0x62, 0x2f, 0x66, 0x66, 0x74, 0x62,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa4, 0x02, 0x0a, 0x0d, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x04, 0x73, 0x74, 0x65, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x74, 0x65, 0x70, 0x52, 0x04, 0x73, 0x74, 0x65,
	0x70, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x3e, 0x0a, 0x0f, 0x63,
	0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x54, 0x61,
	0x73, 0x6b, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x76,
	0x65, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x22, 0x50, 0x0a, 0x04, 0x53,
	0x74, 0x65, 0x70, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00,
	0x12, 0x15, 0x0a, 0x11, 0x44, 0x4f, 0x57, 0x4e, 0x4c, 0x4f, 0x41, 0x44, 0x49, 0x4e, 0x47, 0x5f,
	0x49, 0x4e, 0x50, 0x55, 0x54, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x52, 0x4f, 0x43, 0x45,
	0x53, 0x53, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x14, 0x0a, 0x10, 0x55, 0x50, 0x4c, 0x4f, 0x41,
	0x44, 0x49, 0x4e, 0x47, 0x5f, 0x4f, 0x55, 0x54, 0x50, 0x55, 0x54, 0x10, 0x03, 0x22, 0x51, 0x0a,
	0x11, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64,
	0x22, 0x4f, 0x0a, 0x0f, 0x51, 0x75, 0x69, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x73,
	0x6b, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49,
	0x64, 0x22, 0x6b, 0x0a, 0x0f, 0x46, 0x61, 0x69, 0x6c, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61,
	0x73, 0x6b, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x73, 0x22, 0x3b,
	0x0a, 0x13, 0x46, 0x69, 0x6e, 0x64, 0x46, 0x72, 0x65, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69,
	0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xf0, 0x01, 0x0a, 0x04,
	0x54, 0x61, 0x73, 0x6b, 0x12, 0x22, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x38, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x76,
	0x65, 0x72, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x12, 0x3e, 0x0a, 0x0f, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x4d, 0x65, 0x74, 0x61, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x4d, 0x65,
	0x64, 0x69, 0x61, 0x4d, 0x65, 0x74, 0x61, 0x54, 0x61, 0x73, 0x6b, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x52, 0x0f, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x4d, 0x65, 0x74, 0x61, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x22, 0x3a, 0x0a, 0x08, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b,
	0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x43,
	0x4f, 0x4e, 0x56, 0x45, 0x52, 0x54, 0x5f, 0x56, 0x31, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x4d,
	0x45, 0x44, 0x49, 0x41, 0x5f, 0x4d, 0x45, 0x54, 0x41, 0x5f, 0x56, 0x31, 0x10, 0x02, 0x22, 0x7d,
	0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x12, 0x28, 0x0a, 0x0f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x63, 0x6c, 0x6f,
	0x6e, 0x65, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x69, 0x6e,
	0x70, 0x75, 0x74, 0x52, 0x63, 0x6c, 0x6f, 0x6e, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x2a, 0x0a,
	0x10, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x52, 0x63, 0x6c, 0x6f, 0x6e, 0x65, 0x50, 0x61, 0x74,
	0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x52,
	0x63, 0x6c, 0x6f, 0x6e, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x6f, 0x70, 0x74,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6f, 0x70, 0x74, 0x73, 0x22, 0x6b, 0x0a,
	0x13, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x4d, 0x65, 0x74, 0x61, 0x54, 0x61, 0x73, 0x6b, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x12, 0x28, 0x0a, 0x0f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x63, 0x6c,
	0x6f, 0x6e, 0x65, 0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x69,
	0x6e, 0x70, 0x75, 0x74, 0x52, 0x63, 0x6c, 0x6f, 0x6e, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x2a,
	0x0a, 0x10, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x52, 0x63, 0x6c, 0x6f, 0x6e, 0x65, 0x50, 0x61,
	0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x52, 0x63, 0x6c, 0x6f, 0x6e, 0x65, 0x50, 0x61, 0x74, 0x68, 0x22, 0x81, 0x01, 0x0a, 0x13, 0x43,
	0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x70, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x03, 0x66, 0x70, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70,
	0x65, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x62, 0x69, 0x74, 0x72, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x07, 0x62, 0x69, 0x74, 0x72, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x07,
	0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32, 0xd7, 0x01, 0x0a, 0x06, 0x44, 0x65, 0x61, 0x6c,
	0x65, 0x72, 0x12, 0x2a, 0x0a, 0x0a, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x54, 0x61, 0x73, 0x6b,
	0x12, 0x12, 0x2e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x26,
	0x0a, 0x08, 0x51, 0x75, 0x69, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x10, 0x2e, 0x51, 0x75, 0x69,
	0x74, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x06, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x26, 0x0a, 0x08, 0x46, 0x61, 0x69, 0x6c, 0x54, 0x61,
	0x73, 0x6b, 0x12, 0x10, 0x2e, 0x46, 0x61, 0x69, 0x6c, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x2d,
	0x0a, 0x0c, 0x46, 0x69, 0x6e, 0x64, 0x46, 0x72, 0x65, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x14,
	0x2e, 0x46, 0x69, 0x6e, 0x64, 0x46, 0x72, 0x65, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x05, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x22, 0x00, 0x12, 0x22, 0x0a,
	0x06, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x0e, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x00, 0x42, 0x35, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x77, 0x61, 0x69, 0x6c, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x2f, 0x66, 0x66, 0x74, 0x62, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x64, 0x3b, 0x70,
	0x62, 0xea, 0x02, 0x04, 0x46, 0x66, 0x74, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_distributed_remote_pb_fftb_proto_rawDescOnce sync.Once
	file_pkg_distributed_remote_pb_fftb_proto_rawDescData = file_pkg_distributed_remote_pb_fftb_proto_rawDesc
)

func file_pkg_distributed_remote_pb_fftb_proto_rawDescGZIP() []byte {
	file_pkg_distributed_remote_pb_fftb_proto_rawDescOnce.Do(func() {
		file_pkg_distributed_remote_pb_fftb_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_distributed_remote_pb_fftb_proto_rawDescData)
	})
	return file_pkg_distributed_remote_pb_fftb_proto_rawDescData
}

var file_pkg_distributed_remote_pb_fftb_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_distributed_remote_pb_fftb_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pkg_distributed_remote_pb_fftb_proto_goTypes = []interface{}{
	(NotifyRequest_Step)(0),     // 0: NotifyRequest.Step
	(Task_TaskType)(0),          // 1: Task.TaskType
	(*NotifyRequest)(nil),       // 2: NotifyRequest
	(*FinishTaskRequest)(nil),   // 3: FinishTaskRequest
	(*QuitTaskRequest)(nil),     // 4: QuitTaskRequest
	(*FailTaskRequest)(nil),     // 5: FailTaskRequest
	(*FindFreeTaskRequest)(nil), // 6: FindFreeTaskRequest
	(*Task)(nil),                // 7: Task
	(*ConvertTaskParams)(nil),   // 8: ConvertTaskParams
	(*MediaMetaTaskParams)(nil), // 9: MediaMetaTaskParams
	(*ConvertTaskProgress)(nil), // 10: ConvertTaskProgress
	(*Empty)(nil),               // 11: Empty
}
var file_pkg_distributed_remote_pb_fftb_proto_depIdxs = []int32{
	0,  // 0: NotifyRequest.step:type_name -> NotifyRequest.Step
	10, // 1: NotifyRequest.convertProgress:type_name -> ConvertTaskProgress
	1,  // 2: Task.type:type_name -> Task.TaskType
	8,  // 3: Task.convertParams:type_name -> ConvertTaskParams
	9,  // 4: Task.mediaMetaParams:type_name -> MediaMetaTaskParams
	3,  // 5: Dealer.FinishTask:input_type -> FinishTaskRequest
	4,  // 6: Dealer.QuitTask:input_type -> QuitTaskRequest
	5,  // 7: Dealer.FailTask:input_type -> FailTaskRequest
	6,  // 8: Dealer.FindFreeTask:input_type -> FindFreeTaskRequest
	2,  // 9: Dealer.Notify:input_type -> NotifyRequest
	11, // 10: Dealer.FinishTask:output_type -> Empty
	11, // 11: Dealer.QuitTask:output_type -> Empty
	11, // 12: Dealer.FailTask:output_type -> Empty
	7,  // 13: Dealer.FindFreeTask:output_type -> Task
	11, // 14: Dealer.Notify:output_type -> Empty
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_distributed_remote_pb_fftb_proto_init() }
func file_pkg_distributed_remote_pb_fftb_proto_init() {
	if File_pkg_distributed_remote_pb_fftb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_distributed_remote_pb_fftb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_distributed_remote_pb_fftb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinishTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_distributed_remote_pb_fftb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuitTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_distributed_remote_pb_fftb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FailTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_distributed_remote_pb_fftb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindFreeTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_distributed_remote_pb_fftb_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_distributed_remote_pb_fftb_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConvertTaskParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_distributed_remote_pb_fftb_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MediaMetaTaskParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_distributed_remote_pb_fftb_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConvertTaskProgress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_distributed_remote_pb_fftb_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_distributed_remote_pb_fftb_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_distributed_remote_pb_fftb_proto_goTypes,
		DependencyIndexes: file_pkg_distributed_remote_pb_fftb_proto_depIdxs,
		EnumInfos:         file_pkg_distributed_remote_pb_fftb_proto_enumTypes,
		MessageInfos:      file_pkg_distributed_remote_pb_fftb_proto_msgTypes,
	}.Build()
	File_pkg_distributed_remote_pb_fftb_proto = out.File
	file_pkg_distributed_remote_pb_fftb_proto_rawDesc = nil
	file_pkg_distributed_remote_pb_fftb_proto_goTypes = nil
	file_pkg_distributed_remote_pb_fftb_proto_depIdxs = nil
}
