// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.4
// source: pkg/distributed/remote/pb/fftb.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SegmentType int32

const (
	SegmentType_CONVERT_V1 SegmentType = 0
)

// Enum value maps for SegmentType.
var (
	SegmentType_name = map[int32]string{
		0: "CONVERT_V1",
	}
	SegmentType_value = map[string]int32{
		"CONVERT_V1": 0,
	}
)

func (x SegmentType) Enum() *SegmentType {
	p := new(SegmentType)
	*p = x
	return p
}

func (x SegmentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SegmentType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_distributed_remote_pb_fftb_proto_enumTypes[0].Descriptor()
}

func (SegmentType) Type() protoreflect.EnumType {
	return &file_pkg_distributed_remote_pb_fftb_proto_enumTypes[0]
}

func (x SegmentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SegmentType.Descriptor instead.
func (SegmentType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_distributed_remote_pb_fftb_proto_rawDescGZIP(), []int{0}
}

type ProgressNotification_Step int32

const (
	ProgressNotification_UPLOADING_INPUT    ProgressNotification_Step = 0
	ProgressNotification_DOWNLOADING_INPUT  ProgressNotification_Step = 1
	ProgressNotification_PROCESSING         ProgressNotification_Step = 2
	ProgressNotification_UPLOADING_OUTPUT   ProgressNotification_Step = 3
	ProgressNotification_DOWNLOADING_OUTPUT ProgressNotification_Step = 4
)

// Enum value maps for ProgressNotification_Step.
var (
	ProgressNotification_Step_name = map[int32]string{
		0: "UPLOADING_INPUT",
		1: "DOWNLOADING_INPUT",
		2: "PROCESSING",
		3: "UPLOADING_OUTPUT",
		4: "DOWNLOADING_OUTPUT",
	}
	ProgressNotification_Step_value = map[string]int32{
		"UPLOADING_INPUT":    0,
		"DOWNLOADING_INPUT":  1,
		"PROCESSING":         2,
		"UPLOADING_OUTPUT":   3,
		"DOWNLOADING_OUTPUT": 4,
	}
)

func (x ProgressNotification_Step) Enum() *ProgressNotification_Step {
	p := new(ProgressNotification_Step)
	*p = x
	return p
}

func (x ProgressNotification_Step) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProgressNotification_Step) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_distributed_remote_pb_fftb_proto_enumTypes[1].Descriptor()
}

func (ProgressNotification_Step) Type() protoreflect.EnumType {
	return &file_pkg_distributed_remote_pb_fftb_proto_enumTypes[1]
}

func (x ProgressNotification_Step) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProgressNotification_Step.Descriptor instead.
func (ProgressNotification_Step) EnumDescriptor() ([]byte, []int) {
	return file_pkg_distributed_remote_pb_fftb_proto_rawDescGZIP(), []int{1, 0}
}

type StorageClaimRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Authorization string `protobuf:"bytes,1,opt,name=authorization,proto3" json:"authorization,omitempty"`
	SegmentId     string `protobuf:"bytes,2,opt,name=segmentId,proto3" json:"segmentId,omitempty"`
}

func (x *StorageClaimRequest) Reset() {
	*x = StorageClaimRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_distributed_remote_pb_fftb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StorageClaimRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageClaimRequest) ProtoMessage() {}

func (x *StorageClaimRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_distributed_remote_pb_fftb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageClaimRequest.ProtoReflect.Descriptor instead.
func (*StorageClaimRequest) Descriptor() ([]byte, []int) {
	return file_pkg_distributed_remote_pb_fftb_proto_rawDescGZIP(), []int{0}
}

func (x *StorageClaimRequest) GetAuthorization() string {
	if x != nil {
		return x.Authorization
	}
	return ""
}

func (x *StorageClaimRequest) GetSegmentId() string {
	if x != nil {
		return x.SegmentId
	}
	return ""
}

type ProgressNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Step          ProgressNotification_Step `protobuf:"varint,1,opt,name=step,proto3,enum=ProgressNotification_Step" json:"step,omitempty"`
	Authorization string                    `protobuf:"bytes,2,opt,name=authorization,proto3" json:"authorization,omitempty"`
	Progress      float64                   `protobuf:"fixed64,3,opt,name=progress,proto3" json:"progress,omitempty"`
	SegmentId     string                    `protobuf:"bytes,4,opt,name=segmentId,proto3" json:"segmentId,omitempty"`
}

func (x *ProgressNotification) Reset() {
	*x = ProgressNotification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_distributed_remote_pb_fftb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProgressNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressNotification) ProtoMessage() {}

func (x *ProgressNotification) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_distributed_remote_pb_fftb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressNotification.ProtoReflect.Descriptor instead.
func (*ProgressNotification) Descriptor() ([]byte, []int) {
	return file_pkg_distributed_remote_pb_fftb_proto_rawDescGZIP(), []int{1}
}

func (x *ProgressNotification) GetStep() ProgressNotification_Step {
	if x != nil {
		return x.Step
	}
	return ProgressNotification_UPLOADING_INPUT
}

func (x *ProgressNotification) GetAuthorization() string {
	if x != nil {
		return x.Authorization
	}
	return ""
}

func (x *ProgressNotification) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *ProgressNotification) GetSegmentId() string {
	if x != nil {
		return x.SegmentId
	}
	return ""
}

type FinishSegmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Authorization string `protobuf:"bytes,1,opt,name=authorization,proto3" json:"authorization,omitempty"`
	SegmentId     string `protobuf:"bytes,2,opt,name=segmentId,proto3" json:"segmentId,omitempty"`
}

func (x *FinishSegmentRequest) Reset() {
	*x = FinishSegmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_distributed_remote_pb_fftb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinishSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishSegmentRequest) ProtoMessage() {}

func (x *FinishSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_distributed_remote_pb_fftb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishSegmentRequest.ProtoReflect.Descriptor instead.
func (*FinishSegmentRequest) Descriptor() ([]byte, []int) {
	return file_pkg_distributed_remote_pb_fftb_proto_rawDescGZIP(), []int{2}
}

func (x *FinishSegmentRequest) GetAuthorization() string {
	if x != nil {
		return x.Authorization
	}
	return ""
}

func (x *FinishSegmentRequest) GetSegmentId() string {
	if x != nil {
		return x.SegmentId
	}
	return ""
}

type QuitSegmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Authorization string `protobuf:"bytes,1,opt,name=authorization,proto3" json:"authorization,omitempty"`
	SegmentId     string `protobuf:"bytes,2,opt,name=segmentId,proto3" json:"segmentId,omitempty"`
}

func (x *QuitSegmentRequest) Reset() {
	*x = QuitSegmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_distributed_remote_pb_fftb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuitSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuitSegmentRequest) ProtoMessage() {}

func (x *QuitSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_distributed_remote_pb_fftb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuitSegmentRequest.ProtoReflect.Descriptor instead.
func (*QuitSegmentRequest) Descriptor() ([]byte, []int) {
	return file_pkg_distributed_remote_pb_fftb_proto_rawDescGZIP(), []int{3}
}

func (x *QuitSegmentRequest) GetAuthorization() string {
	if x != nil {
		return x.Authorization
	}
	return ""
}

func (x *QuitSegmentRequest) GetSegmentId() string {
	if x != nil {
		return x.SegmentId
	}
	return ""
}

type FailSegmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Authorization string `protobuf:"bytes,1,opt,name=authorization,proto3" json:"authorization,omitempty"`
	SegmentId     string `protobuf:"bytes,2,opt,name=segmentId,proto3" json:"segmentId,omitempty"`
	Failure       string `protobuf:"bytes,3,opt,name=failure,proto3" json:"failure,omitempty"`
}

func (x *FailSegmentRequest) Reset() {
	*x = FailSegmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_distributed_remote_pb_fftb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FailSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailSegmentRequest) ProtoMessage() {}

func (x *FailSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_distributed_remote_pb_fftb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailSegmentRequest.ProtoReflect.Descriptor instead.
func (*FailSegmentRequest) Descriptor() ([]byte, []int) {
	return file_pkg_distributed_remote_pb_fftb_proto_rawDescGZIP(), []int{4}
}

func (x *FailSegmentRequest) GetAuthorization() string {
	if x != nil {
		return x.Authorization
	}
	return ""
}

func (x *FailSegmentRequest) GetSegmentId() string {
	if x != nil {
		return x.SegmentId
	}
	return ""
}

func (x *FailSegmentRequest) GetFailure() string {
	if x != nil {
		return x.Failure
	}
	return ""
}

type FindFreeSegmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Authorization string `protobuf:"bytes,1,opt,name=authorization,proto3" json:"authorization,omitempty"`
}

func (x *FindFreeSegmentRequest) Reset() {
	*x = FindFreeSegmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_distributed_remote_pb_fftb_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindFreeSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindFreeSegmentRequest) ProtoMessage() {}

func (x *FindFreeSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_distributed_remote_pb_fftb_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindFreeSegmentRequest.ProtoReflect.Descriptor instead.
func (*FindFreeSegmentRequest) Descriptor() ([]byte, []int) {
	return file_pkg_distributed_remote_pb_fftb_proto_rawDescGZIP(), []int{5}
}

func (x *FindFreeSegmentRequest) GetAuthorization() string {
	if x != nil {
		return x.Authorization
	}
	return ""
}

type Segment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type SegmentType `protobuf:"varint,1,opt,name=type,proto3,enum=SegmentType" json:"type,omitempty"`
	Id   string      `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// string orderId = 3;
	ConvertParams *ConvertSegmentParams `protobuf:"bytes,4,opt,name=convertParams,proto3" json:"convertParams,omitempty"`
}

func (x *Segment) Reset() {
	*x = Segment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_distributed_remote_pb_fftb_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Segment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Segment) ProtoMessage() {}

func (x *Segment) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_distributed_remote_pb_fftb_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Segment.ProtoReflect.Descriptor instead.
func (*Segment) Descriptor() ([]byte, []int) {
	return file_pkg_distributed_remote_pb_fftb_proto_rawDescGZIP(), []int{6}
}

func (x *Segment) GetType() SegmentType {
	if x != nil {
		return x.Type
	}
	return SegmentType_CONVERT_V1
}

func (x *Segment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Segment) GetConvertParams() *ConvertSegmentParams {
	if x != nil {
		return x.ConvertParams
	}
	return nil
}

type ConvertSegmentParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoCodec       string `protobuf:"bytes,1,opt,name=videoCodec,proto3" json:"videoCodec,omitempty"`
	HwAccel          string `protobuf:"bytes,2,opt,name=hwAccel,proto3" json:"hwAccel,omitempty"`
	VideoBitRate     string `protobuf:"bytes,3,opt,name=videoBitRate,proto3" json:"videoBitRate,omitempty"`
	VideoQuality     int32  `protobuf:"varint,4,opt,name=videoQuality,proto3" json:"videoQuality,omitempty"`
	Preset           string `protobuf:"bytes,5,opt,name=preset,proto3" json:"preset,omitempty"`
	Scale            string `protobuf:"bytes,6,opt,name=scale,proto3" json:"scale,omitempty"`
	KeyframeInterval int32  `protobuf:"varint,7,opt,name=keyframeInterval,proto3" json:"keyframeInterval,omitempty"`
	Muxer            string `protobuf:"bytes,8,opt,name=muxer,proto3" json:"muxer,omitempty"`
	Position         int32  `protobuf:"varint,9,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *ConvertSegmentParams) Reset() {
	*x = ConvertSegmentParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_distributed_remote_pb_fftb_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConvertSegmentParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertSegmentParams) ProtoMessage() {}

func (x *ConvertSegmentParams) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_distributed_remote_pb_fftb_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertSegmentParams.ProtoReflect.Descriptor instead.
func (*ConvertSegmentParams) Descriptor() ([]byte, []int) {
	return file_pkg_distributed_remote_pb_fftb_proto_rawDescGZIP(), []int{7}
}

func (x *ConvertSegmentParams) GetVideoCodec() string {
	if x != nil {
		return x.VideoCodec
	}
	return ""
}

func (x *ConvertSegmentParams) GetHwAccel() string {
	if x != nil {
		return x.HwAccel
	}
	return ""
}

func (x *ConvertSegmentParams) GetVideoBitRate() string {
	if x != nil {
		return x.VideoBitRate
	}
	return ""
}

func (x *ConvertSegmentParams) GetVideoQuality() int32 {
	if x != nil {
		return x.VideoQuality
	}
	return 0
}

func (x *ConvertSegmentParams) GetPreset() string {
	if x != nil {
		return x.Preset
	}
	return ""
}

func (x *ConvertSegmentParams) GetScale() string {
	if x != nil {
		return x.Scale
	}
	return ""
}

func (x *ConvertSegmentParams) GetKeyframeInterval() int32 {
	if x != nil {
		return x.KeyframeInterval
	}
	return 0
}

func (x *ConvertSegmentParams) GetMuxer() string {
	if x != nil {
		return x.Muxer
	}
	return ""
}

func (x *ConvertSegmentParams) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type StorageClaim struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *StorageClaim) Reset() {
	*x = StorageClaim{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_distributed_remote_pb_fftb_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StorageClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageClaim) ProtoMessage() {}

func (x *StorageClaim) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_distributed_remote_pb_fftb_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageClaim.ProtoReflect.Descriptor instead.
func (*StorageClaim) Descriptor() ([]byte, []int) {
	return file_pkg_distributed_remote_pb_fftb_proto_rawDescGZIP(), []int{8}
}

func (x *StorageClaim) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_distributed_remote_pb_fftb_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_distributed_remote_pb_fftb_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pkg_distributed_remote_pb_fftb_proto_rawDescGZIP(), []int{9}
}

var File_pkg_distributed_remote_pb_fftb_proto protoreflect.FileDescriptor

var file_pkg_distributed_remote_pb_fftb_proto_rawDesc = []byte{
	0x0a, 0x24, 0x70, 0x6b, 0x67, 0x2f, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x64, 0x2f, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x2f, 0x70, 0x62, 0x2f, 0x66, 0x66, 0x74, 0x62,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x59, 0x0a, 0x13, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a,
	0x0d, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x22, 0x98, 0x02, 0x0a, 0x14, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x04, 0x73, 0x74,
	0x65, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x50, 0x72, 0x6f, 0x67, 0x72,
	0x65, 0x73, 0x73, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x53, 0x74, 0x65, 0x70, 0x52, 0x04, 0x73, 0x74, 0x65, 0x70, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x70, 0x0a, 0x04, 0x53, 0x74,
	0x65, 0x70, 0x12, 0x13, 0x0a, 0x0f, 0x55, 0x50, 0x4c, 0x4f, 0x41, 0x44, 0x49, 0x4e, 0x47, 0x5f,
	0x49, 0x4e, 0x50, 0x55, 0x54, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x44, 0x4f, 0x57, 0x4e, 0x4c,
	0x4f, 0x41, 0x44, 0x49, 0x4e, 0x47, 0x5f, 0x49, 0x4e, 0x50, 0x55, 0x54, 0x10, 0x01, 0x12, 0x0e,
	0x0a, 0x0a, 0x50, 0x52, 0x4f, 0x43, 0x45, 0x53, 0x53, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x14,
	0x0a, 0x10, 0x55, 0x50, 0x4c, 0x4f, 0x41, 0x44, 0x49, 0x4e, 0x47, 0x5f, 0x4f, 0x55, 0x54, 0x50,
	0x55, 0x54, 0x10, 0x03, 0x12, 0x16, 0x0a, 0x12, 0x44, 0x4f, 0x57, 0x4e, 0x4c, 0x4f, 0x41, 0x44,
	0x49, 0x4e, 0x47, 0x5f, 0x4f, 0x55, 0x54, 0x50, 0x55, 0x54, 0x10, 0x04, 0x22, 0x5a, 0x0a, 0x14,
	0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65,
	0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73,
	0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x58, 0x0a, 0x12, 0x51, 0x75, 0x69, 0x74,
	0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24,
	0x0a, 0x0d, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x22, 0x72, 0x0a, 0x12, 0x46, 0x61, 0x69, 0x6c, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c,
	0x0a, 0x09, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66,
	0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x22, 0x3e, 0x0a, 0x16, 0x46, 0x69, 0x6e, 0x64, 0x46, 0x72,
	0x65, 0x65, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x24, 0x0a, 0x0d, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69,
	0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x78, 0x0a, 0x07, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x20, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0c, 0x2e, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x3b, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x43, 0x6f, 0x6e,
	0x76, 0x65, 0x72, 0x74, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x22, 0xa4, 0x02, 0x0a, 0x14, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x53, 0x65, 0x67, 0x6d,
	0x65, 0x6e, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x76, 0x69, 0x64,
	0x65, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x76,
	0x69, 0x64, 0x65, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x63, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x77, 0x41,
	0x63, 0x63, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x68, 0x77, 0x41, 0x63,
	0x63, 0x65, 0x6c, 0x12, 0x22, 0x0a, 0x0c, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x42, 0x69, 0x74, 0x52,
	0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x76, 0x69, 0x64, 0x65, 0x6f,
	0x42, 0x69, 0x74, 0x52, 0x61, 0x74, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x76, 0x69, 0x64, 0x65, 0x6f,
	0x51, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x76,
	0x69, 0x64, 0x65, 0x6f, 0x51, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x70,
	0x72, 0x65, 0x73, 0x65, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x65,
	0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x6b, 0x65, 0x79,
	0x66, 0x72, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x10, 0x6b, 0x65, 0x79, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x76, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x75, 0x78, 0x65, 0x72, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x75, 0x78, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x20, 0x0a, 0x0c, 0x53, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x2a, 0x1d, 0x0a, 0x0b, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x4f, 0x4e, 0x56, 0x45, 0x52, 0x54, 0x5f, 0x56, 0x31, 0x10,
	0x00, 0x32, 0xfd, 0x02, 0x0a, 0x06, 0x44, 0x65, 0x61, 0x6c, 0x65, 0x72, 0x12, 0x3d, 0x0a, 0x14,
	0x47, 0x65, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x43,
	0x6c, 0x61, 0x69, 0x6d, 0x12, 0x14, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x43, 0x6c,
	0x61, 0x69, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x53, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x1a, 0x41,
	0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x53, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x12, 0x14, 0x2e, 0x53, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0d, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x22, 0x00,
	0x12, 0x30, 0x0a, 0x0d, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x15, 0x2e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x22, 0x00, 0x12, 0x2c, 0x0a, 0x0b, 0x51, 0x75, 0x69, 0x74, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x13, 0x2e, 0x51, 0x75, 0x69, 0x74, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00,
	0x12, 0x2c, 0x0a, 0x0b, 0x46, 0x61, 0x69, 0x6c, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x12,
	0x13, 0x2e, 0x46, 0x61, 0x69, 0x6c, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x36,
	0x0a, 0x0f, 0x46, 0x69, 0x6e, 0x64, 0x46, 0x72, 0x65, 0x65, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x17, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x46, 0x72, 0x65, 0x65, 0x53, 0x65, 0x67, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x08, 0x2e, 0x53, 0x65, 0x67,
	0x6d, 0x65, 0x6e, 0x74, 0x22, 0x00, 0x12, 0x29, 0x0a, 0x06, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x12, 0x15, 0x2e, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x00, 0x42, 0x35, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x77, 0x61, 0x69, 0x6c, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x2f, 0x66, 0x66, 0x74, 0x62, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x64, 0x3b, 0x70,
	0x62, 0xea, 0x02, 0x04, 0x46, 0x66, 0x74, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_distributed_remote_pb_fftb_proto_rawDescOnce sync.Once
	file_pkg_distributed_remote_pb_fftb_proto_rawDescData = file_pkg_distributed_remote_pb_fftb_proto_rawDesc
)

func file_pkg_distributed_remote_pb_fftb_proto_rawDescGZIP() []byte {
	file_pkg_distributed_remote_pb_fftb_proto_rawDescOnce.Do(func() {
		file_pkg_distributed_remote_pb_fftb_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_distributed_remote_pb_fftb_proto_rawDescData)
	})
	return file_pkg_distributed_remote_pb_fftb_proto_rawDescData
}

var file_pkg_distributed_remote_pb_fftb_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_distributed_remote_pb_fftb_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pkg_distributed_remote_pb_fftb_proto_goTypes = []interface{}{
	(SegmentType)(0),               // 0: SegmentType
	(ProgressNotification_Step)(0), // 1: ProgressNotification.Step
	(*StorageClaimRequest)(nil),    // 2: StorageClaimRequest
	(*ProgressNotification)(nil),   // 3: ProgressNotification
	(*FinishSegmentRequest)(nil),   // 4: FinishSegmentRequest
	(*QuitSegmentRequest)(nil),     // 5: QuitSegmentRequest
	(*FailSegmentRequest)(nil),     // 6: FailSegmentRequest
	(*FindFreeSegmentRequest)(nil), // 7: FindFreeSegmentRequest
	(*Segment)(nil),                // 8: Segment
	(*ConvertSegmentParams)(nil),   // 9: ConvertSegmentParams
	(*StorageClaim)(nil),           // 10: StorageClaim
	(*Empty)(nil),                  // 11: Empty
}
var file_pkg_distributed_remote_pb_fftb_proto_depIdxs = []int32{
	1,  // 0: ProgressNotification.step:type_name -> ProgressNotification.Step
	0,  // 1: Segment.type:type_name -> SegmentType
	9,  // 2: Segment.convertParams:type_name -> ConvertSegmentParams
	2,  // 3: Dealer.GetInputStorageClaim:input_type -> StorageClaimRequest
	2,  // 4: Dealer.AllocateOutputStorageClaim:input_type -> StorageClaimRequest
	4,  // 5: Dealer.FinishSegment:input_type -> FinishSegmentRequest
	5,  // 6: Dealer.QuitSegment:input_type -> QuitSegmentRequest
	6,  // 7: Dealer.FailSegment:input_type -> FailSegmentRequest
	7,  // 8: Dealer.FindFreeSegment:input_type -> FindFreeSegmentRequest
	3,  // 9: Dealer.Notify:input_type -> ProgressNotification
	10, // 10: Dealer.GetInputStorageClaim:output_type -> StorageClaim
	10, // 11: Dealer.AllocateOutputStorageClaim:output_type -> StorageClaim
	11, // 12: Dealer.FinishSegment:output_type -> Empty
	11, // 13: Dealer.QuitSegment:output_type -> Empty
	11, // 14: Dealer.FailSegment:output_type -> Empty
	8,  // 15: Dealer.FindFreeSegment:output_type -> Segment
	11, // 16: Dealer.Notify:output_type -> Empty
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_distributed_remote_pb_fftb_proto_init() }
func file_pkg_distributed_remote_pb_fftb_proto_init() {
	if File_pkg_distributed_remote_pb_fftb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_distributed_remote_pb_fftb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StorageClaimRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_distributed_remote_pb_fftb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProgressNotification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_distributed_remote_pb_fftb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinishSegmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_distributed_remote_pb_fftb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuitSegmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_distributed_remote_pb_fftb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FailSegmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_distributed_remote_pb_fftb_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindFreeSegmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_distributed_remote_pb_fftb_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Segment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_distributed_remote_pb_fftb_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConvertSegmentParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_distributed_remote_pb_fftb_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StorageClaim); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_distributed_remote_pb_fftb_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_distributed_remote_pb_fftb_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_distributed_remote_pb_fftb_proto_goTypes,
		DependencyIndexes: file_pkg_distributed_remote_pb_fftb_proto_depIdxs,
		EnumInfos:         file_pkg_distributed_remote_pb_fftb_proto_enumTypes,
		MessageInfos:      file_pkg_distributed_remote_pb_fftb_proto_msgTypes,
	}.Build()
	File_pkg_distributed_remote_pb_fftb_proto = out.File
	file_pkg_distributed_remote_pb_fftb_proto_rawDesc = nil
	file_pkg_distributed_remote_pb_fftb_proto_goTypes = nil
	file_pkg_distributed_remote_pb_fftb_proto_depIdxs = nil
}
