require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'lib/pb/**/*'
    - 'db/schema.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/models/**/*'
    - 'app/handlers/**/*'
    - 'app/controllers/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/GuardClause:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Metrics/CyclomaticComplexity:
  Max: 10

Style/ClassCheck:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/Lambda:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Style/HashAsLastArrayItem:
  Exclude:
    - 'app/controllers/**/*'

Style/IfUnlessModifier:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Rails/InverseOf:
  Enabled: true
