# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pkg/distributed/remote/pb/fftb.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("pkg/distributed/remote/pb/fftb.proto", :syntax => :proto3) do
    add_message "NotifyRequest" do
      optional :step, :enum, 1, "NotifyRequest.Step"
      optional :authorization, :string, 2
      optional :taskId, :string, 3
      optional :progress, :double, 4
      optional :convertProgress, :message, 5, "ConvertTaskProgress"
    end
    add_enum "NotifyRequest.Step" do
      value :UNKNOWN, 0
      value :DOWNLOADING_INPUT, 1
      value :PROCESSING, 2
      value :UPLOADING_OUTPUT, 3
    end
    add_message "FinishTaskRequest" do
      optional :authorization, :string, 1
      optional :taskId, :string, 2
    end
    add_message "QuitTaskRequest" do
      optional :authorization, :string, 1
      optional :taskId, :string, 2
    end
    add_message "FailTaskRequest" do
      optional :authorization, :string, 1
      optional :taskId, :string, 2
      repeated :failures, :string, 3
    end
    add_message "FindFreeTaskRequest" do
      optional :authorization, :string, 1
    end
    add_message "Task" do
      optional :type, :enum, 1, "Task.TaskType"
      optional :id, :string, 2
      optional :convertParams, :message, 4, "ConvertTaskParams"
      optional :mediaMetaParams, :message, 5, "MediaMetaTaskParams"
    end
    add_enum "Task.TaskType" do
      value :UNKNOWN, 0
      value :CONVERT_V1, 1
      value :MEDIA_META_V1, 2
    end
    add_message "ConvertTaskParams" do
      optional :inputRclonePath, :string, 1
      optional :outputRclonePath, :string, 2
      repeated :opts, :string, 3
    end
    add_message "MediaMetaTaskParams" do
      optional :inputRclonePath, :string, 1
      optional :outputRclonePath, :string, 2
    end
    add_message "ConvertTaskProgress" do
      optional :fps, :double, 1
      optional :frame, :int64, 2
      optional :speed, :double, 3
      optional :bitrate, :double, 4
      optional :time, :int64, 5
    end
    add_message "Empty" do
    end
  end
end

module Fftb
  NotifyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("NotifyRequest").msgclass
  NotifyRequest::Step = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("NotifyRequest.Step").enummodule
  FinishTaskRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("FinishTaskRequest").msgclass
  QuitTaskRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("QuitTaskRequest").msgclass
  FailTaskRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("FailTaskRequest").msgclass
  FindFreeTaskRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("FindFreeTaskRequest").msgclass
  Task = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Task").msgclass
  Task::TaskType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Task.TaskType").enummodule
  ConvertTaskParams = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ConvertTaskParams").msgclass
  MediaMetaTaskParams = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("MediaMetaTaskParams").msgclass
  ConvertTaskProgress = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ConvertTaskProgress").msgclass
  Empty = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Empty").msgclass
end
