# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pkg/distributed/remote/pb/fftb.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("pkg/distributed/remote/pb/fftb.proto", :syntax => :proto3) do
    add_message "StorageClaimRequest" do
      optional :authorization, :string, 1
      optional :segmentId, :string, 2
    end
    add_message "ProgressNotification" do
      optional :step, :enum, 1, "ProgressNotification.Step"
      optional :authorization, :string, 2
      optional :progress, :double, 3
      optional :segmentId, :string, 4
    end
    add_enum "ProgressNotification.Step" do
      value :UPLOADING_INPUT, 0
      value :DOWNLOADING_INPUT, 1
      value :PROCESSING, 2
      value :UPLOADING_OUTPUT, 3
      value :DOWNLOADING_OUTPUT, 4
    end
    add_message "FinishSegmentRequest" do
      optional :authorization, :string, 1
      optional :segmentId, :string, 2
    end
    add_message "QuitSegmentRequest" do
      optional :authorization, :string, 1
      optional :segmentId, :string, 2
    end
    add_message "FailSegmentRequest" do
      optional :authorization, :string, 1
      optional :segmentId, :string, 2
      optional :failure, :string, 3
    end
    add_message "FindFreeSegmentRequest" do
      optional :authorization, :string, 1
    end
    add_message "Segment" do
      optional :type, :enum, 1, "SegmentType"
      optional :id, :string, 2
      optional :convertParams, :message, 4, "ConvertSegmentParams"
    end
    add_message "ConvertSegmentParams" do
      optional :videoCodec, :string, 1
      optional :hwAccel, :string, 2
      optional :videoBitRate, :string, 3
      optional :videoQuality, :int32, 4
      optional :preset, :string, 5
      optional :scale, :string, 6
      optional :keyframeInterval, :int32, 7
      optional :muxer, :string, 8
      optional :position, :int32, 9
    end
    add_message "StorageClaim" do
      optional :url, :string, 1
    end
    add_message "Empty" do
    end
    add_enum "SegmentType" do
      value :CONVERT_V1, 0
    end
  end
end

module Fftb
  StorageClaimRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("StorageClaimRequest").msgclass
  ProgressNotification = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ProgressNotification").msgclass
  ProgressNotification::Step = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ProgressNotification.Step").enummodule
  FinishSegmentRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("FinishSegmentRequest").msgclass
  QuitSegmentRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("QuitSegmentRequest").msgclass
  FailSegmentRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("FailSegmentRequest").msgclass
  FindFreeSegmentRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("FindFreeSegmentRequest").msgclass
  Segment = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Segment").msgclass
  ConvertSegmentParams = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ConvertSegmentParams").msgclass
  StorageClaim = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("StorageClaim").msgclass
  Empty = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Empty").msgclass
  SegmentType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("SegmentType").enummodule
end
